### PR TITLE
Update .gitignore files in FE and BE

### PR DESCRIPTION
**Pull request by edzhabs**
Update .gitignore files in FE and BE.

source: https://github.com/github/gitignore/blob/main/Node.gitignore

### CODE REVIEW

**Comment by 22tofu** [comment]
resolve conflict edward

**Comment by edzhabs** [comment]
> resolve conflict edward

yes master ron. currently reviewing the code.

**Comment by edzhabs** [comment]
Resolved conflicts

**Comment by beefysalad** [comment]
LGTM. Thanks for this @edzhabs

**Pull request merged**
